
services:
  - type: web
    name: shilomultiservices
    runtime: python

    buildCommand: ./build.sh

    startCommand: gunicorn config.wsgi:application

    envVars:

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        fromDatabase:
          name: shilomultiservices-db
          property: connectionString

      - key: ADMIN_EMAIL
        value: "contact@shilomultiservices.com"

      - key: DEFAULT_FROM_EMAIL
        value: "contact@shilomultiservices.com"

      - key: EMAIL_HOST
        sync: false

      - key: EMAIL_HOST_USER
        sync: false

      - key: EMAIL_HOST_PASSWORD
        sync: false

      - key: EMAIL_PORT
        value: "587"

      - key: EMAIL_USE_TLS
        value: "True"


databases:

  - name: shilomultiservices-db
