# Generated by Django 5.2.17 on 2026-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='Un avantage par ligne.'),
        ),
        migrations.AddField(
            model_name='service',
            name='frequency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='included_services',
            field=models.TextField(blank=True, help_text='Une prestation par ligne.'),
        ),
        migrations.AddField(
            model_name='service',
            name='target_clients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
    ]
